config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'events#index'
  resources :users, only: :index

  get '/user/:id', to: 'users#show', as: :user

  resources :events do
    member do
      get 'rsvp'
      get 'cancel_rsvp'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', :foreign_key => 'creator_id'
  validates :title, :description, :date, :time, :location, presence: true
  has_many :rsvps, foreign_key: :attended_event_id
  has_many :attendees, through: :rsvps

  scope :past, -> { where('date < ?', Date.today).order(date: :desc) }
  scope :future, -> { where('date > ?', Date.today).order(:date) }
end

app/models/rsvp.rb
class Rsvp < ApplicationRecord
  belongs_to :attendee, class_name: 'User', :foreign_key => 'attendee_id'
  belongs_to :attended_event, class_name: 'Event', :foreign_key => 'attended_event_id'
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :created_events, foreign_key: :creator_id, class_name: 'Event', dependent: :destroy
  has_many :rsvps, foreign_key: :attendee_id
  has_many :attended_events, through: :rsvps
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
     def configure_permitted_parameters
          devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}
          devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
     end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      redirect_to @event, notice: "Your event was created"
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to @event, notice: "Your event was updated"
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end

  def rsvp
    @event = Event.find(params[:id])
    if @event.attendees.include?(current_user)
      redirect_to @event, notice: "You are already on the list"
    else
      @event.attendees << current_user
      redirect_to @event
    end
  end

  def cancel_rsvp
    @event = Event.find(params[:id])
    @event.attendees.delete(current_user)
    redirect_to @event, notice: "You are no longer attending this event"
  end


  private

  def event_params
    params.require(:event).permit(:title, :description, :date, :time, :location)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with model: @event, local: true do |f| %>
  <% if @event.errors.any? %>
    <ul>
      <% @event.errors.full_messages.each do |error| %>
        <li> <%= error %> </li>
      <% end %>
    </ul>
  <% end %>
  <div class="form-group">
    <%= f.text_field :title, placeholder: "Event title", class: "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.text_area :description, placeholder: "Event description", class: "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.text_field :location, placeholder: "Event location", class: "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.date_field :date, class: "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.time_field :time, class: "form-control"  %>
  </div>
  <%= f.submit class: "btn btn-outline-primary" %>
<% end %>

app/views/events/edit.html.erb
<h1>Edit Event</h1>
<%= render 'form' %>

app/views/events/index.html.erb
<div class="row mb-4">
  <div class="col">
    <h1>Upcoming Events</h1>
  </div>
  <div class="col">
    <%= link_to 'Create Event', new_event_path, class: "btn btn-primary float-right" %>
  </div>
</div>

<div class="row mb-5">
  <% Event.future.each do |event| %>
  <div class="col-md-4 mb-4">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title"><%= event.title.titleize %></h4>
          <p class="small text-muted"><%= event.date.strftime("%B %-d, %Y") %></p>
          <p class="card-text"><%= event.description.truncate(100) %></p>
          <%= link_to 'Learn More', event_path(event), class: "btn btn-outline-primary btn-block" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<p class="text-muted">PAST EVENTS</p>
<div class="row">
  <% Event.past.each do |event| %>
  <div class="col-md-3 mb-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= event.title.titleize %></h5>
          <p class="small text-muted"><%= event.date.strftime("%B %-d, %Y") %></p>
          <p class="card-text"><%= event.description.truncate(50) %></p>
          <%= link_to 'Learn More', event_path(event), class: "btn btn-outline-primary btn-block" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/events/new.html.erb
<h1>Create Event</h1>

<%= render 'form' %>

app/views/events/show.html.erb
<% if @event.date < Time.now %>
  <div class="alert alert-secondary" role="alert">Registration for this event is now closed</div>
<% end %>

<div class="row mb-4">
  <div class="col">
    <h1><%= @event.title.titleize %></h1>
  </div>
  <div class="col text-right">
    <% if current_user == @event.creator %>
      <%= link_to 'Edit', edit_event_path, class: "btn btn-outline-secondary" %>
      <%= link_to 'Delete', event_path, method: :delete, class: "btn btn-outline-secondary",
                            data: { confirm: "Delete this event?"} %>
    <% elsif @event.attendees.include?(current_user) %>
      <%= link_to 'Cancel RSVP', cancel_rsvp_event_path, class: "btn btn-outline-secondary" %>
    <% else %>
      <%= link_to 'RSVP', rsvp_event_path, class: "btn btn-primary" unless @event.date < Time.now %>
    <% end %>
  </div>
</div>

<div class="row mb-4">
  <div class="col">
    <div class="card">
      <div class="row no-gutters">

        <div class="col-md-8">
          <div class="card-body">

            <p class="card-text text-muted"> <%= @event.description %> </p>
          </div>
        </div>

        <div class="col-md-4">
          <div class="card-body">
            <p class="text-muted">
              <i class="far fa-user-circle text-dark fa-lg mr-1"></i>
                Created by <%= link_to @event.creator.name, user_path(@event.creator) %>
            </p>
            <p class="text-muted">
              <i class="far fa-calendar-alt text-dark fa-lg mr-1"></i>
              <%= @event.date.strftime("%B %-d, %Y at %l:%M %p") %>
            </p>
            <p class="text-muted">
              <i class="fas fa-map-marker-alt text-dark fa-lg mr-1"></i> <%= @event.location %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<p class=" text-muted mb-4">ATTENDEES</p>

<% if @event.attendees.empty? %>
<div class="list-group">
  <li class="list-group-item text-muted">This event has no attendees yet</li>
</div>
<% else %>
  <div class="list-group">
    <% @event.attendees.each do |attendee| %>
    <li class="list-group-item"> <%= attendee.name %> </li>
    <% end %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container">
    <%= link_to 'Private Events', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'Calendar', events_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Members', users_path, class: "nav-link" %>
        </li>
      </ul>
      <span class="navbar-nav">
        <% if user_signed_in? %>
          <%= link_to 'My Events', user_path(current_user), class: "nav-item nav-link" %>
          <%= link_to "Account", edit_user_registration_path, class: "nav-item nav-link" %>
          <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-item nav-link" %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-item nav-link" %>
          <%= link_to "Login", new_user_session_path, class: "nav-item nav-link" %>
        <% end %>
      </span>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body style="background-color: #F6F9FC;">
    <%= render 'layouts/navbar' %>
    <div class="container mt-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/index.html.erb
<h1 class="mb-4">Members</h1>

<div class="list-group">
  <% @users.each do |user| %>
    <%= link_to user.name, user_path(user), class: "list-group-item list-group-item-action" %>
  <% end %>
</div>

app/views/users/show.html.erb
<h1 class="mb-4"> <%= @user.name %> </h1>

<div class="row">
  <div class="col-md mb-4">
    <p class="text-muted"> <%= pluralize(@user.created_events.count, 'event').upcase %> CREATED</p>
    <div class="list-group mt-3">
        <% @user.created_events.each do |event| %>
          <%= link_to event.title, event_path(event), class: "list-group-item list-group-item-action" %>
        <% end %>
    </div>
  </div>
  <div class="col-md mb-4">
    <p class="text-muted"> <%= pluralize(@user.attended_events.count, 'event').upcase %> ATTENDED</p>
    <div class="list-group mt-3">
        <% @user.attended_events.each do |event| %>
          <%= link_to event.title, event_path(event), class: "list-group-item list-group-item-action" %>
        <% end %>
    </div>
  </div>
</div>